#!/bin/bash

while test "$1" != ""
do
   case $1 in
      --record|-r)

      url='http://metal-only.de/listen.pls'


export DAUER="$2"

export datei="$(mplayer -frames 0 -quiet "$url" 2>&1 | awk -F\'  '/^ICY Info/{print $2}')"

mplayer -quiet -dumpstream $url &
sleep $DAUER
killall mplayer

mv ~/stream.dump ~/"$datei"
                ;;
      --recordlater|-rl)
export WARTEN="$2"
sleep $WARTEN

      ;;
      --exit|-x)
      exit
      ;;
      --help|-h)
#      echo "Hilfe Menü"
echo " Verwendung: "
echo "metal-only --parameter / --longparameter "
echo "Parameter:"
echo " -r / --record * [Aufnahme des Streams für festgelgte Zeit *]"
echo "'*' ist hierbei durch die Zeit zu ersetzen: *h *m *s [*h = *Stunden; *m = *Minuten; *s = *Sekunden]"
echo " -rl | --recordlater * [Aufnahme des Streams ab bestimmtem Zeitpunkt]"
echo "'*' ist hierbei durch die Zeit bis zum Beginn der Aufnahme zu ersetzen: *h *m *s [*h = *Stunden; *m = *Minuten; *s = *Sekunden]"
echo "Um das Aufnehmen zu starten, muss der Parameter -r übergeben werden (siehe -r / --record)"
echo "-x / --exit [Beenden des Scripts nach dem Ausführen der vorangegangenen Parameter]"
echo "Parameter hinter -x werden nicht mehr Berücksichtigt!"
echo "-h / --help [Zeigt dieses Menü an]"
echo "-p / --plan [Zeigt den wöchentlichen Sendeplan von Metal Only an]"
echo "-pr / --playrecord [Spielt die zuvor mit -r aufgenommene Sendung ab]"
echo "Kann nicht verwendet werden, wenn keine Sendung mit -r aufgenommen wurde!"
echo "-hp / --homepage [Ruft die Startseite www.metal-only.de im Standardbrowser auf]"
echo "-v / --version [Zeigt die Nummer der Version und deren Änderung sowie die Kontaktdaten an]"
      ;;
      --plan|-p)
      curl -s "http://www.metal-only.de/?action=plan" |w3m -dump -T text/html|head -n 20|cut -c 31-108
      ;;
      --playrecord|-pr)
      mplayer ~/"$datei"
      ;;
      --homepage|-hp)
if [[ -f $(which firefox 2>/dev/null) ]]
    then
   firefox www.metal-only.de
    else
   if [[ -f $(which chromium 2>/dev/null) ]]
     then 
       chromium www.metal-only.de
     else
       if   [[ -f $(which opera 2>/dev/null) ]]
         then
      opera www.metal-only.de
      else
        echo "Ihr Browser konnte leider nicht ermittelt werden!"
        echo "Zur Fehlerbehebung beschreiben Sie das Problem in einer e-mail an mich!"
        exec metal-only -v
fi
   fi
       fi
      ;;
                --version|-v)
                echo "Version: 1.1 beta"
echo "Änderungen: "
echo "Hinzugefügte Optionen: Verbesserte Darstellung von --help; Aufnahme ab bestimmtem Zeitpunkt mit -rl; Aufrufen des Sendeplans auf der Homepage"
echo "'/bin/bash' - Script"
echo "-------------------------------------------------------------------------------------------------------------------------------------------"
echo "Kontakt für Fehlerberichte: "
echo "mail an sebi@tuximail.de oder Nachricht an Todestoast im Metal Only Forum"
echo "-------------------------------------------------------------------------------------------------------------------------------------------"
echo "Denk immer daran: Metal Only braucht jede Spende!"
                ;;
      --homepage-plan|-hp-plan)
if [[ -f $(which firefox 2>/dev/null) ]]
    then
        firefox www.metal-only.de/?action=plan
    else
        if [[ -f $(which chromium 2>/dev/null) ]]
          then 
            chromium www.metal-only.de/?action=plan
          else
            if   [[ -f $(which opera 2>/dev/null) ]]
              then
                opera www.metal-only.de/?action=plan
                else
                  echo "Ihr Browser konnte leider nicht ermittelt werden!"
                  echo "Zur Fehlerbehebung beschreiben Sie das Problem in einer e-mail an mich!"
                  exec metal-only -v
fi
   fi
      fi
      ;;
   esac
   shift
done

url='http://metal-only.de/listen.pls'

while read -r line
do
        date +%H:%M:%S
        echo "$line" | sed -r "s/.*StreamTitle='([^']+)'.*/\1/"
done < <(mplayer -quiet "$url" 2>&1 | sed -nu '/^ICY/ p')
